name: bootcamp_level
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.10
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attr=2.5.1
  - attrs=23.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.12.2
  - bleach=4.1.0
  - blosc=1.21.5
  - boltons=23.0.0
  - branca=0.6.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.20.1
  - ca-certificates=2023.08.22
  - cairo=1.18.0
  - certifi=2023.7.22
  - cffi=1.16.0
  - cfitsio=4.2.0
  - charset-normalizer=3.3.0
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.7.4
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.1.1
  - cryptography=41.0.4
  - cycler=0.12.1
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - esda=2.5.0
  - exceptiongroup=1.0.4
  - executing=0.8.3
  - expat=2.5.0
  - fiona=1.9.3
  - fmt=10.1.1
  - folium=0.14.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.43.1
  - freetype=2.12.1
  - freexl=2.0.0
  - gdal=3.6.4
  - geographiclib=1.52
  - geopandas=0.14.0
  - geopandas-base=0.14.0
  - geopy=2.4.0
  - geos=3.12.0
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - glib=2.78.0
  - glib-tools=2.78.0
  - graphite2=1.3.13
  - gst-plugins-base=1.22.6
  - gstreamer=1.22.6
  - h3-py=3.7.6
  - h3pandas=0.2.3
  - harfbuzz=8.2.1
  - hdf4=4.2.15
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib-resources=6.1.0
  - importlib_resources=6.1.0
  - ipykernel=6.25.0
  - ipython=8.15.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.4
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.17
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_server=1.13.5
  - jupyterlab=3.3.2
  - jupyterlab_server=2.10.3
  - jupyterlab_widgets=3.0.5
  - kealib=1.5.2
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.6.2
  - libblas=3.9.0
  - libboost-headers=1.82.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.69
  - libcblas=3.9.0
  - libclang=15.0.7
  - libclang13=15.0.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.4.0
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.4
  - libflac=1.4.3
  - libgcc-ng=13.2.0
  - libgcrypt=1.10.1
  - libgdal=3.6.4
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.0
  - libgoogle-cloud=2.12.0
  - libgpg-error=1.47
  - libgrpc=1.58.1
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnetcdf=4.9.2
  - libnghttp2=1.57.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.24
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.4
  - libprotobuf=4.24.3
  - libpysal=4.8.0
  - librttopo=1.1.0
  - libsndfile=1.2.2
  - libsodium=1.0.18
  - libsolv=0.7.25
  - libspatialindex=1.9.3
  - libspatialite=5.0.1
  - libsqlite=3.43.2
  - libssh2=1.11.0
  - libstdcxx-ng=13.2.0
  - libsystemd0=254
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libvorbis=1.3.7
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.6.0
  - libxml2=2.11.5
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.1
  - mapclassify=2.6.1
  - markupsafe=2.1.3
  - matplotlib=3.8.0
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - minizip=4.0.1
  - mistune=0.8.4
  - mpg123=1.32.3
  - munch=4.0.0
  - munkres=1.1.4
  - mysql-common=8.0.33
  - mysql-libs=8.0.33
  - nbclassic=0.5.5
  - nbconvert=5.5.0
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=3.1
  - notebook=6.5.4
  - notebook-shim=0.2.2
  - nspr=4.35
  - nss=3.94
  - numpy=1.26.0
  - openjpeg=2.5.0
  - openssl=3.1.3
  - packaging=23.2
  - pandas=2.1.1
  - pandoc=2.12
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.40
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.2.1
  - pixman=0.42.2
  - platformdirs=3.11.0
  - pluggy=1.3.0
  - ply=3.11
  - poppler=23.08.0
  - poppler-data=0.4.12
  - postgresql=15.4
  - proj=9.3.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.18
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3.post1
  - pyzmq=23.2.0
  - qt-main=5.15.8
  - qtconsole=5.4.2
  - qtpy=2.2.0
  - re2=2023.03.02
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - rtree=1.0.1
  - ruamel.yaml=0.17.35
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.3.1
  - scipy=1.11.3
  - send2trash=1.8.0
  - setuptools=68.0.0
  - shapely=2.0.1
  - sip=6.7.11
  - six=1.16.0
  - snappy=1.1.10
  - sniffio=1.2.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.2.0
  - terminado=0.17.1
  - testpath=0.6.0
  - threadpoolctl=3.2.0
  - tiledb=2.16.3
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.7.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - tzcode=2023c
  - tzdata=2023c
  - unicodedata2=15.1.0
  - uriparser=0.9.7
  - urllib3=2.0.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.41.2
  - widgetsnbextension=4.0.5
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xerces-c=3.2.4
  - xkeyboard-config=2.40
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.7
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xyzservices=2023.10.0
  - xz=5.4.2
  - yaml-cpp=0.7.0
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.21.0
  - zstd=1.5.5
